### ISSUE TITLE
'test' does not work

### ISSUE THREAD

**Issue by mikecann** [yusukebe/hono-minimal#2]
1. Clone the repo
2. Run `yarn install`
3. Run `yarn test` 
4. Notice you get the following error:

```
❯ yarn jest
yarn run v1.22.4
$ C:\dev\markd\gangbusters-discord-bot\node_modules\.bin\jest
● Validation Error:

  Module C:\dev\markd\gangbusters-discord-bot\node_modules\jest-circus\runner.js in the testRunner option was not found.
         <rootDir> is: C:\dev\markd\gangbusters-discord-bot

  Configuration Documentation:
  https://jestjs.io/docs/configuration

error Command failed with exit code 1.
```

A quick google turns up this: https://github.com/facebook/jest/issues/10297#issuecomment-1017307039

If one comments out `resolver: 'jest-node-exports-resolver',` in `jest.config.js` you then get this error:

```
 FAIL  src/index.test.ts
  ● Test suite failed to run

    Cannot find module 'hono/powered-by' from 'src/index.ts'

    Require stack:
      src/index.ts
      src/index.test.ts

      22 | })
      23 |
    > 24 | // Routing
         |                     ^
      25 | app.get('/', (c) => c.html('<h1>Hello Hono!</h1>'))
      26 | app.get('/auth/*', (c) => c.text('You are authorized'))
      27 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/index.ts:24:25)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.441 s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by yusukebe** [comment]
Hi @mikecann 

Unfortunately, I can't reproduce the error on my environment :(

How about do this: 

```
yarn add -D jest-circus
```

and, run the test.

**Comment by mikecann** [comment]
No that didnt work for me.

I decided to use es-build jest for faster builds. 

This is my config:

```
module.exports = {
  testEnvironment: "miniflare",
  transform: {
    "^.+\\.tsx?$": [
      "esbuild-jest",
      {
        sourcemap: true,
        loaders: {
          ".spec.ts": "tsx",
        },
      },
    ],
  },
};
```

Most tests run fine, but it seems to get stuck at the hono logger import:

```
 FAIL  src/index.test.ts
  ● Test suite failed to run

    Cannot find module 'hono/logger' from 'src/index.ts'

    Require stack:
      src/index.ts
      src/index.test.ts

      1 | import { Hono } from "hono";
    > 2 | import { logger } from "hono/logger";
        |                        ^
      3 | import { basicAuth } from "hono/basic-auth";
      4 | import { createRequestValidator } from "./discord/requestValidation";
      5 | import { Interaction, InteractionType } from "./discord/types";

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/index.ts:2:24)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       5 passed, 5 total
Snapshots:   1 passed, 1 total
Time:        0.865 s, estimated 1 s
Ran all test suites.
error Command failed with exit code 1.
```

Must be some sort of import mismatch from jest, I can work around it tho by not testing that file

**Comment by yusukebe** [comment]
Hi @mikecann. Thank you for trying.

It seem to be fixed on Jest **28.x** not released generally yet. Jest **28.x** supports `exports in package.json`. 

https://github.com/facebook/jest/pull/12373
https://github.com/facebook/jest/pull/11961

The good ways are wait until Jest 28.x releasing or use [pre-release version](https://github.com/facebook/jest/releases).

**Comment by mikecann** [comment]
awesome thanks for that, appreciate you taking the time to look into it.

hono is great by the way, thanks :)

**Comment by yusukebe** [comment]
Thank you to you too!

**Comment by yusukebe** [comment]
@mikecann 

Hi! Jest **v28.0.0** has been released! It succeeds to test without `jest-node-exports-resolver`!
